### ISSUE TITLE
Flaky Test:  AuthenticationTests.AuthTypes_RequireAuth_Success(authType: Negotiate)

### ISSUE THREAD

**Issue by mikeharder** [aspnet/HttpSysServer#341]
Test `AuthenticationTests.AuthTypes_RequireAuth_Success(authType: Negotiate)` failed in a CI build:

```
System.Threading.Tasks.TaskCanceledException : A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.HttpSys.AuthenticationTests.<SendRequestAsync>d__20.MoveNext() in C:\BuildAgent\work\2b0c8ce712895332\.r\HttpSysServer\test\Microsoft.AspNetCore.Server.HttpSys.FunctionalTests\AuthenticationTests.cs:line 489
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.HttpSys.AuthenticationTests.<AuthTypes_RequireAuth_Success>d__7.MoveNext() in C:\BuildAgent\work\2b0c8ce712895332\.r\HttpSysServer\test\Microsoft.AspNetCore.Server.HttpSys.FunctionalTests\AuthenticationTests.cs:line 168
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

http://aspnetci/viewLog.html?buildId=199872&tab=buildResultsDiv&buildTypeId=XPlat_Windows_Win8_Universe

**Comment by muratg** [comment]
Assigning to @JunTaoLuo for investigation.

**Comment by JunTaoLuo** [comment]
I no longer see any failures for this test on the CI, it has 100% success rate: http://aspnetci/project.html?projectId=XPlat&buildTypeId=&tab=testDetails&testNameId=-6445676963988030601&order=START_DATE_DESC&branch_XPlat=__all_branches__&itemsCount=50

Closing now since I can't repro.
