### ISSUE TITLE
ArgumentNullException("chars") is thrown when iterating HeaderDictionary

### ISSUE THREAD

**Issue by kadukf** [aspnet/HttpSysServer#381]
Iterating over Request.Headers throws ArgumentNullException in case the web hosting uses WebListener/HttpSysListener and the request contains a header with empty value, e.g. 

GET /api/values HTTP/1.1
If-None-Match:

It fails when calling UTF8Encoding.GetChars(byte* bytes, int byteCount, char* chars, int charCount) because chars point to IntPtr.Zero.

In case of Kestrel, all is fine.

**Comment by Tratcher** [comment]
Can you share the full stack trace? I assume the issue is here:
https://github.com/aspnet/HttpSysServer/blob/015de501ad3dd1056a68b9460667265deb5d6454/src/Microsoft.AspNetCore.Server.HttpSys/RequestProcessing/NativeRequestContext.cs#L275

What client are you using? Most won't send empty headers.

**Comment by kadukf** [comment]
Stack trace:

   at System.Text.UTF8Encoding.GetChars(Byte* bytes, Int32 byteCount, Char* chars, Int32 charCount)
   at Microsoft.Net.Http.Server.HeaderEncoding.GetString(SByte* pBytes, Int32 byteCount)
   at Microsoft.Net.Http.Server.NativeRequestContext.GetKnownHeader(HttpSysRequestHeader header)
   at Microsoft.Net.Http.Server.RequestHeaders.get_IfNoneMatch()
   at Microsoft.Net.Http.Server.RequestHeaders.<PropertiesEnumerable>d__201.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__58`1.MoveNext()

**Comment by kadukf** [comment]
We have a clients which send us such payload. We migrated from OWIN to ASPNETCORE and we have this regression. We have a nasty hack implemented using reflection (class Microsoft.Net.Http.Server.HeaderEncoding, field Encoding) but we want to get rid of this hack.
