### ISSUE TITLE
RegisterPrefix failed - The process cannot access the file because it is being used...

### ISSUE THREAD

**Issue by ylbillyli** [aspnet/HttpSysServer#429]
Not sure if related to https://github.com/Azure/service-fabric-issues/issues/707
```
var host = new WebHostBuilder()
                        .UseHttpSys()
                        .UseConfiguration(config)
                        .UseContentRoot(Directory.GetCurrentDirectory())
                        .UseStartup<Startup>()
                        .UseUrls("http://+:80/mysite/")
                        .Build();

host.Run();
```
Debug logs:
```
info: Microsoft.AspNetCore.Server.HttpSys.HttpSysListener[0]
      Start
info: Microsoft.AspNetCore.Server.HttpSys.HttpSysListener[0]
      Listening on prefix: http://+:80/mysite/
fail: Microsoft.AspNetCore.Server.HttpSys.HttpSysListener[0]
      Start
Microsoft.AspNetCore.Server.HttpSys.HttpSysException (0x80004005): The process cannot access the file because it is being used by another process
   at Microsoft.AspNetCore.Server.HttpSys.UrlGroup.RegisterPrefix(String uriPrefix, Int32 contextId)
   at Microsoft.AspNetCore.Server.HttpSys.UrlPrefixCollection.RegisterAllPrefixes(UrlGroup urlGroup)
   at Microsoft.AspNetCore.Server.HttpSys.HttpSysListener.Start()
GeoZone.exe Program.cs failed Microsoft.AspNetCore.Server.HttpSys.HttpSysException (0x80004005): The process cannot access the file because it is being used by another process
   at Microsoft.AspNetCore.Server.HttpSys.UrlGroup.RegisterPrefix(String uriPrefix, Int32 contextId)
   at Microsoft.AspNetCore.Server.HttpSys.UrlPrefixCollection.RegisterAllPrefixes(UrlGroup urlGroup)
   at Microsoft.AspNetCore.Server.HttpSys.HttpSysListener.Start()
   at Microsoft.AspNetCore.Server.HttpSys.MessagePump.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.<StartAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.<RunAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.<RunAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at Program.Main()
```

**Comment by Tratcher** [comment]
Something else one the machine has claimed port 80 and doesn't want to share...

**Comment by muratg** [comment]
@ylbillyli if you figure out if that's not it, please reopen.

**Comment by ylbillyli** [comment]
@muratg Sorry I forgot about this thread and email has been sending to my previous work email. Anyway, please feel free to close this issue. 

I could not remember exactly what was the solution but it could be as you suggested we have both OWIN and dotnetcore services and we share port 80 fine for multiple dotnetcore apps, but for those OWIN apps, the OWIN version of HttpSys does not willing to share port 80 with dotnetcore apps, despite they both uses HttpSys.
