### ISSUE TITLE
Unlisted Dependency

### ISSUE THREAD

**Issue by TonyValenti** [aspnet/HttpSysServer#436]
Hi ASPNet Team,
I am trying to use the HttpSysServer in a project and I'm getting the error message below.

Itseems as though my project is missing a reference, but I'm noticing that System.Threading.Overlapped is not listed as a package dependency for this project.  Are there any other unlisted dependencies I should add?

```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Threading.Overlapped, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Threading.Overlapped, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Microsoft.AspNetCore.Server.HttpSys.RequestQueue..ctor(UrlGroup urlGroup, ILogger logger)
   at Microsoft.AspNetCore.Server.HttpSys.HttpSysListener..ctor(HttpSysOptions options, ILoggerFactory loggerFactory)
   at Microsoft.AspNetCore.Server.HttpSys.MessagePump..ctor(IOptions`1 options, ILoggerFactory loggerFactory, IAuthenticationSchemeProvider authentication)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass22_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureServer()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at AlphaDrive.Services.AspNetCore.AspNetCoreExtension.<Start>d__14.MoveNext() in C:\Users\Tony Valenti\source\repos\AlphaDrive\AlphaDrive.Services.AspNetCore\AspNetCoreExtension.cs:line 60
```

**Comment by Tratcher** [comment]
What package version is this?

**Comment by TonyValenti** [comment]
I am using this DLL:
C:\Users\Tony Valenti\source\repos\AlphaDrive\packages\Microsoft.AspNetCore.Server.HttpSys.2.0.3\lib\netstandard2.0\Microsoft.AspNetCore.Server.HttpSys.dll

and it has this version:
2.0.3.0

**Comment by Tratcher** [comment]
And you're running on .NET Core 2 or .NET 4.x?

**Comment by TonyValenti** [comment]
I'm not sure how to answer that question.  The library is a cross platform library that I'm compiling for .NET 4.6.1.

Oddly, my app works fine on Windows 10, but on Windows 7 I get the error mentioned.

**Comment by TonyValenti** [comment]
Actually, I guess I see the error happening on windows 10 too. Apparently it is just not happening on my dev box.

**Comment by Tratcher** [comment]
This seems like an issue specific to your project dependency setup. Can you share a dummy project on github that reproduces it?

**Comment by muratg** [comment]
We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
