### ISSUE TITLE
Flaky test: Server_MultipleStopAsyncCallsCompleteOnSingleCancellation_FirstToken_Success

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/HttpSysServer#443]
This test [fails occasionally](http://aspnetci/viewLog.html?buildId=440171&tab=buildResultsDiv&buildTypeId=XPlat_Windows_Win2008r2_Universe#testNameId3205445488278035764), seemingly specific to 2008.

```
Assert.True() Failure
Expected: True
Actual:   False
   at Microsoft.AspNetCore.Server.HttpSys.ServerTests.<Server_MultipleStopAsyncCallsCompleteOnSingleCancellation_FirstToken_Success>d__18.MoveNext() in C:\BuildAgent\work\33bdfc1cae7b2a38\modules\HttpSysServer\test\Microsoft.AspNetCore.Server.HttpSys.FunctionalTests\ServerTests.cs:line 498
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

Future instances of this failure will appear [here](http://aspnetci/project.html?projectId=XPlat&buildTypeId=XPlat_Windows_Win2008r2_Universe&tab=testDetails&testNameId=3205445488278035764&order=START_DATE_DESC&branch_XPlat=__all_branches__&itemsCount=50).

**Comment by ryanbrandenburg** [comment]
This is still happening and has a roughly 9% failure rate on Win2008 Universe.
