### ISSUE TITLE
Test failure: Server_SetConnectionLimitChangeAfterStarted_Success

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/HttpSysServer#476]
This test [fails](http://aspnetci/viewLog.html?buildId=562898&buildTypeId=Lite_UniverseTest) occasionally with the following error:
```
Assert.Throws() Failure
Expected: typeof(System.Net.Http.HttpRequestException)
Actual:   (No exception was thrown)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.AspNetCore.Server.HttpSys.ServerTests.<Server_SetConnectionLimitChangeAfterStarted_Success>d__15.MoveNext() in /_/test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/ServerTests.cs:line 405
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on master.

CC @Eilon (because the bot doesn't know who else to pick)

This issue was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by Eilon** [comment]
@muratg please assign.

**Comment by Tratcher** [comment]
I did some code cleanup that should help here.
