### ISSUE TITLE
Test failure: Server_ShutdownDuringRequest_Success

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/HttpSysServer#488]
This issue was made automatically. If there is a problem contact ryanbrandenburg.

This test [failed](https://dnceng.visualstudio.com/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_build/results?buildId=37834) with the following error:

```
System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.Net.WebException : Unable to connect to the remote server
-------- System.Net.Sockets.SocketException : No connection could be made because the target machine actively refused it 127.0.0.1:5131
```

Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on release/2.2.

CC Eilon

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

**Comment by Eilon** [comment]
```
2018-10-31T17:34:54.7458398Z   Failed   Microsoft.AspNetCore.Server.HttpSys.ServerTests.Server_ShutdownDuringRequest_Success
2018-10-31T17:34:54.7462350Z   Error Message:
2018-10-31T17:34:54.7464988Z    System.Net.Http.HttpRequestException : An error occurred while sending the request.
2018-10-31T17:34:54.7481567Z   ---- System.Net.WebException : Unable to connect to the remote server
2018-10-31T17:34:54.7481820Z   -------- System.Net.Sockets.SocketException : No connection could be made because the target machine actively refused it 127.0.0.1:5131
2018-10-31T17:34:54.7481895Z   Stack Trace:
2018-10-31T17:34:54.7482020Z      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2018-10-31T17:34:54.7482183Z      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-10-31T17:34:54.7482295Z      at Microsoft.AspNetCore.Server.HttpSys.ServerTests.<SendRequestAsync>d__23.MoveNext() in /_/test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/ServerTests.cs:line 638
2018-10-31T17:34:54.7482415Z   --- End of stack trace from previous location where exception was thrown ---
2018-10-31T17:34:54.7482891Z      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2018-10-31T17:34:54.7483234Z      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-10-31T17:34:54.7483366Z      at Microsoft.AspNetCore.Server.HttpSys.ServerTests.<Server_ShutdownDuringRequest_Success>d__3.MoveNext() in /_/test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/ServerTests.cs:line 85
2018-10-31T17:34:54.7483505Z   --- End of stack trace from previous location where exception was thrown ---
2018-10-31T17:34:54.7483799Z      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2018-10-31T17:34:54.7484122Z      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-10-31T17:34:54.7485553Z   --- End of stack trace from previous location where exception was thrown ---
2018-10-31T17:34:54.7485878Z      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2018-10-31T17:34:54.7486035Z      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-10-31T17:34:54.7486300Z   --- End of stack trace from previous location where exception was thrown ---
2018-10-31T17:34:54.7486367Z      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2018-10-31T17:34:54.7486464Z      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-10-31T17:34:54.7486526Z   ----- Inner Stack Trace -----
2018-10-31T17:34:54.7486613Z      at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
2018-10-31T17:34:54.7486680Z      at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
2018-10-31T17:34:54.7486737Z   ----- Inner Stack Trace -----
2018-10-31T17:34:54.7486832Z      at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
2018-10-31T17:34:54.7486896Z      at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
2018-10-31T17:34:54.7487003Z      at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
```

@muratg can you assign?

**Comment by muratg** [comment]
@Tratcher could you take a look please?
